name: covid-19-box
on:
  schedule:
    - cron: '6 */6 * * *'  # every 6h at 6 min past the hour
  push:
    branches: master
jobs:
  covid-19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "dvc update && dvc repro"
        uses: ./
        with:
           countries: ${{ secrets.countries }}
           gh_token: ${{ secrets.gh_token }}
           gist_id: ${{ secrets.gist_id }}
      - name: Commit changes
        run: |
          git config user.name "Casper da Costa-Luis"
          git config user.email casper.dcl@physics.org
          git checkout -- .dvc/config
          git commit -am "automatic update [ci skip]" || :
          git push
